### PR TITLE
week5 firsttry

### PR DESCRIPTION
**Pull request by otismwo86**

### CODE REVIEW

**Comment by otismwo86** [comment]
老師您好，我是莫翔宇
http://18.209.3.48:8000/
http://18.209.3.48:8000/attraction/10
http://18.209.3.48:8000/booking

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Attraction image should extend to full width in mobile layout of the booking page.
2. Fill name and email for user automatically in the booking page.
3. Response format of Booking API should align with API specs.

**Comment by otismwo86** [comment]
老師您好，我已經修復以上問題

**Review by cwpeng — CHANGES_REQUESTED** [review]
Request format of Booking API should align with API specs.

**Comment by otismwo86** [comment]
老師您好，我已調整request body，麻煩您在看一次

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
