### PR TITLE
week4 first

### PR DESCRIPTION
**Pull request by otismwo86**

### CODE REVIEW

**Comment by otismwo86** [comment]
老師您好。我是莫翔宇
http://18.209.3.48:8000/
http://18.209.3.48:8000/attraction/2

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should check user sign-in status by calling User API, not just check localStorage in the front-end. (how about I put any text in localStorage through developer tools?)

**Comment by otismwo86** [comment]
老師您好，我已修復以上問題

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
