### PR TITLE
payment firsttry

### PR DESCRIPTION
**Pull request by otismwo86**

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Where is your testing URL?

**Comment by otismwo86** [comment]
老師不好意思剛剛好像沒有貼上
http://18.209.3.48:8000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
Clear booking data after successful ordering.

**Comment by otismwo86** [comment]
老師您好
我已修復以上問題

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
